"""AgentDescent: a parallel, self-evolving framework for accelerating RSI.

A systematic port of the parallel-training playbook (data/tensor/pipeline
parallelism, parameter servers, decoupled/async RL, partial rollout) onto
recursive self-improvement, where the "parameters" are a library of evolvable
artifacts (skills, prompts, harness modules, verifiers) and the "gradients" are
diffs carrying evidence cards.

Every module cites the design-spec section it implements ("design doc, section
4.2"). The spec itself is **not shipped in this repository**; ``docs/`` is written
against the code that came out of it, so read ``docs/concepts.md`` for the *why*
and ``docs/architecture.md`` for how the sections map onto the modules.
"""

from .evolvable import (
    Contract,
    ContractError,
    stable_hash,
    Diff,
    EvidenceCard,
    Evolvable,
    VersionVector,
    vv_dominates,
    vv_staleness,
)
from .ledger import (
    Ledger, Snapshot, CASConflict, ContractRejected, GitError, LedgerFailure,
)
from .verifier import ThreeLayerVerifier, VerifierBudget
from . import backends, dataloader          # submodules: agentdescent.dataloader.hf_rows(...)
from .dataloader import Dataset, split_dataset
from .sampling import DifficultyWeighted, RoundRobin, TaskSampler
from .scheduler import (
    AuditScheduler,
    DurationEstimator,
    ResumeQueue,
    TaskCluster,
    TaskScheduler,
    fifo_makespan,
    lpt_schedule,
)
from .governance import (
    FAST_MAX, FROZEN_IDS, Layer, classify, assert_mutable, GovernanceError,
    L1SerialGate,
)
from .aggregator import (
    Aggregator,
    AggregatorContractError,
    MergeOutcome,
    diffs_conflict,
    diffs_contradict,
    fuse_diffs,
    AggregatorConfig,
    AggregatorProtocol,
    AggregatorFactory,
    MergeReport,
    EvidenceBuffer,
)
from .staleness import (
    StaleAction,
    StalenessPolicy,
    FullStaleness,
    GuardedStaleness,
    ReflectiveStaleness,
    get_policy,
)
from .policies import (
    AcceptDecision,
    AcceptancePolicy,
    ConflictPolicy,
    FusionPolicy,
    LedgerProtocol,
    MergeContext,
    Policies,
    Promotion,
    PromotionPolicy,
    ProposalContext,
    ProposalPolicy,
    Sandbox,
    SandboxProvider,
    SandboxSpec,
    VerifierProtocol,
)
from .evalcache import CacheProtocol, FileCache, MemoryCache
from .executor import Executor, Result, ThreadExecutor
from .sandbox import LocalWorkspaceSandbox, SandboxPool, WorkspaceProvider
from .supervisor import ProcessExecutor
from .workspec import Ref, RefError, RolloutSpec
from . import rewards                      # agentdescent.rewards.last_number(...)
from .skill import evolve_skill
from .filetree import (
    TreeError,
    TreeSpec,
    canonical,
    load_tree,
    materialize,
    parse_tree,
    tree_summary,
)
from .treestrategy import EDIT_PROTOCOL, FileTree, parse_edits, tree_reflector
from .runners import LAYOUTS, TEST_FAILURE_MARKER, code_runner, tree_runner
from .skilldir import evolve_agent_code, evolve_agent_dir, evolve_skill_dir
from .worker import Worker
from .orchestrator import AgentDescent, RoundStat, run_fork_baseline
from .agents import (
    AgentError,
    Completion,
    Usage,
    claude,
    echo,
    from_callable,
    claude_code,
    cli_agent,
    codex,
    metered,
    openai_compatible,
    with_retries,
)
from .agents import WorkspaceAgent
from .evolution import (
    Agent,
    LLMAgent,
    reflector,
    Task,
    EvolvingArtifact,
    Strategy,
    AppendRules,
    KeyedRules,
    SingleSlot,
    EvolutionResult,
    ProposalContractError,
    RewardContractError,
    SOLVED,
    tasks_from,
    RoundInfo,
    evolve,
    claude_agent,
    rule_id,
)
from .async_evolve import async_evolve
from .async_runtime import AsyncAgentDescent, AsyncConfig, AsyncStats
from .parallel import (
    ParallelMode,
    ParallelStrategy,
    WorkUnit,
    DataParallel,
    TensorParallel,
    PipelineParallel,
    TensorParallelMerge,
    PipelineChain,
    SectionViolation,
    assign_key_sections,
    assign_sections,
    section_of,
    shard_round_robin,
)

__version__ = "0.3.0"

__all__ = [
    "Contract",
    "ContractError",
    "stable_hash",
    "Diff",
    "EvidenceCard",
    "Evolvable",
    "VersionVector",
    "vv_dominates",
    "vv_staleness",
    "Ledger",
    "Snapshot",
    "CASConflict",
    "GitError",
    "LedgerFailure",
    "ContractRejected",
    "ThreeLayerVerifier",
    "VerifierBudget",
    "AuditScheduler",
    "Dataset",
    "split_dataset",
    "backends",
    "dataloader",
    "DifficultyWeighted",
    "RoundRobin",
    "TaskSampler",
    "ResumeQueue",
    "DurationEstimator",
    "lpt_schedule",
    "fifo_makespan",
    "TaskCluster",
    "TaskScheduler",
    "Layer",
    "classify",
    "assert_mutable",
    "GovernanceError",
    "FAST_MAX",
    "FROZEN_IDS",
    "L1SerialGate",
    "Aggregator",
    "AggregatorConfig",
    "AggregatorProtocol",
    "AggregatorFactory",
    "MergeReport",
    "MergeOutcome",
    "AggregatorContractError",
    "diffs_conflict",
    "diffs_contradict",
    "fuse_diffs",
    "EvidenceBuffer",
    "StaleAction",
    "StalenessPolicy",
    "FullStaleness",
    "GuardedStaleness",
    "ReflectiveStaleness",
    "get_policy",
    "Policies",
    "AcceptancePolicy",
    "AcceptDecision",
    "ConflictPolicy",
    "FusionPolicy",
    "PromotionPolicy",
    "Promotion",
    "ProposalPolicy",
    "ProposalContext",
    "MergeContext",
    "VerifierProtocol",
    "LedgerProtocol",
    "SandboxSpec",
    "SandboxPool",
    "Executor",
    "CacheProtocol",
    "MemoryCache",
    "FileCache",
    "ThreadExecutor",
    "ProcessExecutor",
    "Result",
    "Ref",
    "RefError",
    "RolloutSpec",
    "WorkspaceProvider",
    "LocalWorkspaceSandbox",
    "SandboxProvider",
    "Sandbox",
    "Worker",
    "AgentDescent",
    "RoundStat",
    "run_fork_baseline",
    "AsyncAgentDescent",
    "AsyncConfig",
    "AsyncStats",
    "ParallelMode",
    "ParallelStrategy",
    "WorkUnit",
    "DataParallel",
    "TensorParallel",
    "PipelineParallel",
    "TensorParallelMerge",
    "PipelineChain",
    "SectionViolation",
    "assign_sections",
    "assign_key_sections",
    "section_of",
    "shard_round_robin",
    "Completion",
    "codex",
    "claude_code",
    "cli_agent",
    "WorkspaceAgent",
    "AgentError",
    "Usage",
    "metered",
    "claude",
    "echo",
    "from_callable",
    "openai_compatible",
    "with_retries",
    "Agent",
    "LLMAgent",
    "reflector",
    "Task",
    "EvolvingArtifact",
    "Strategy",
    "AppendRules",
    "KeyedRules",
    "SingleSlot",
    "EvolutionResult",
    "RewardContractError",
    "ProposalContractError",
    "SOLVED",
    "tasks_from",
    "RoundInfo",
    "evolve",
    "evolve_skill",
    "TreeError",
    "TreeSpec",
    "canonical",
    "load_tree",
    "materialize",
    "parse_tree",
    "tree_summary",
    "EDIT_PROTOCOL",
    "FileTree",
    "parse_edits",
    "tree_reflector",
    "LAYOUTS",
    "TEST_FAILURE_MARKER",
    "code_runner",
    "tree_runner",
    "evolve_skill_dir",
    "evolve_agent_dir",
    "evolve_agent_code",
    "async_evolve",
    "claude_agent",
    "rule_id",
]
