"""AgentDescent: a parallel, self-evolving framework for accelerating RSI.

A systematic port of the parallel-training playbook (data/tensor/pipeline
parallelism, parameter servers, decoupled/async RL, partial rollout) onto
recursive self-improvement, where the "parameters" are a library of evolvable
artifacts (skills, prompts, harness modules, verifiers) and the "gradients" are
diffs carrying evidence cards.

Every module cites the design-spec section it implements ("design doc, section
4.2"). The spec itself is **not shipped in this repository**; ``docs/`` is written
against the code that came out of it, so read ``docs/concepts.md`` for the *why*
and ``docs/architecture.md`` for how the sections map onto the modules.
"""

from .core.evolvable import (
    Contract,
    ContractError,
    stable_hash,
    Diff,
    EvidenceCard,
    Evolvable,
    VersionVector,
    vv_dominates,
    vv_staleness,
)
from .merge.ledger import (
    Ledger, Snapshot, CASConflict, ContractRejected, GitError, LedgerFailure,
)
from .evaluate.verifier import ThreeLayerVerifier, VerifierBudget
from .audit import (
    AuditedReward, AuditRecord, AuditStore, DeferredOracle, GoldAnswer,
    NullOracle, Purpose, RenderTap, resolve_from_mapping, verifier_fingerprint,
    residual_bias,
)
from .actors import backends
from .actors import dataloader    # submodules: agentdescent.actors.dataloader.hf_rows(...)
from .actors.dataloader import Dataset, split_dataset
from .merge.advantage import (
    AdaptiveTrustRegion,
    AdvantageAcceptance,
    AdvantageConflict,
    GroupAdvantage,
    StableDistanceAcceptance,
    TrustRegion,
    state_distance,
)
from .merge.defaults import DefaultConflict, DefaultFusion
from .merge.fusion import KeepContradictions, ReflectiveFusion, reflective_merge
from .schedule.sampling import DifficultyWeighted, RoundRobin, TaskSampler
from .schedule.selection import (
    Archive,
    Beam,
    Candidate,
    CostEfficient,
    MCTS,
    MultiHeadUnsupported,
    ParetoFrontier,
    SelectionContext,
    SelectionPolicy,
    SingleHead,
    pareto_front,
)
from .schedule.scheduler import (
    AuditScheduler,
    DurationEstimator,
    ResumeQueue,
    TaskCluster,
    TaskScheduler,
    fifo_makespan,
    lpt_schedule,
)
from .merge.governance import (
    FAST_MAX, FROZEN_IDS, Layer, classify, assert_mutable, GovernanceError,
    L1SerialGate,
)
from .merge.aggregator import (
    Aggregator,
    AggregatorContractError,
    MergeOutcome,
    diffs_conflict,
    diffs_contradict,
    fuse_diffs,
    AggregatorConfig,
    AggregatorProtocol,
    AggregatorFactory,
    MergeReport,
    EvidenceBuffer,
)
from .schedule.population import PopulationAggregator, population_factory
from .merge.staleness import (
    StaleAction,
    StalenessPolicy,
    FullStaleness,
    GuardedStaleness,
    ReflectiveStaleness,
    get_policy,
)
from .core.policies import (
    AcceptDecision,
    AcceptancePolicy,
    ConflictPolicy,
    FusionPolicy,
    FusionTrial,
    LedgerProtocol,
    MergeContext,
    Policies,
    Promotion,
    PromotionPolicy,
    ProposalContext,
    ProposalPolicy,
    Sandbox,
    SandboxProvider,
    SandboxSpec,
    VerifierProtocol,
)
from .evaluate.evalcache import CacheProtocol, FileCache, MemoryCache
from .observe.checkpoint import (
    save_checkpoint,
    load_checkpoint,
    restore_checkpoint,
    restore_early_stop,
    clear_checkpoints,
    list_checkpoints,
)
from .observe.budget import BudgetGovernor, CallBudget, budgeted_completion
from .runtime.executor import Executor, Result, ThreadExecutor
from .runtime.sandbox import LocalWorkspaceSandbox, SandboxPool, WorkspaceProvider
from .runtime.sandbox_shared import SharedSandboxPool
from .runtime.supervisor import ProcessExecutor
from .core.workspec import Ref, RefError, RolloutSpec
from .actors import rewards                # agentdescent.actors.rewards.last_number(...)
from .actors.rewards import SCORERS, scorer, command_scorer, GraderError
from .loop.meta import (
    SLOTS, SLOT_PROTOCOLS, MetaOutcome, ParamSlot, PrioritySelection, PRIORITY_SEED,
    SlotSpec, SourceSlot, auc, compile_policy_source, compile_priority, evolve_problem,
    final_reward, meta_evolve, meta_validate, policy_source, priority_selection,
    rollouts_to, seed_source, slot_reflector, transfer_ratio,
)
from .artifacts.filetree import (
    TreeError,
    TreeSpec,
    canonical,
    load_tree,
    materialize,
    parse_tree,
    tree_summary,
)
from .artifacts.treestrategy import EDIT_PROTOCOL, FileTree, parse_edits, tree_reflector
from .actors.runners import (
    LAYOUTS, PLUGIN_FROZEN, PLUGIN_HOSTS, TEST_FAILURE_MARKER, PluginHost, code_runner,
    gated_reward, plugin_runner, tree_runner,
)
from .reference.orchestrator import AgentDescent, RoundStat, run_fork_baseline
from .actors.agents import (
    AgentError,
    Completion,
    Usage,
    claude,
    echo,
    from_callable,
    claude_code,
    cli_agent,
    codex,
    dsh,
    opencode,
    metered,
    openai_compatible,
    anthropic_compatible,
    with_retries,
)
from .actors.agents import WorkspaceAgent, worker_env
from .loop.evolution import (
    Agent,
    LLMAgent,
    reflector,
    Task,
    EvolvingArtifact,
    Strategy,
    AppendRules,
    KeyedRules,
    SingleSlot,
    EvolutionResult,
    FusionStats,
    ProposalContractError,
    RewardContractError,
    SOLVED,
    tasks_from,
    RoundInfo,
    evolve,
    claude_agent,
    rule_id,
)
from .loop.async_evolve import async_evolve
from .core.evolvespec import EvolveSpec, SpecError, compose, load_spec, run_spec
from .reference.async_runtime import AsyncAgentDescent, AsyncConfig, AsyncStats
from .observe import baselines              # agentdescent.observe.baselines.merge_of_n(...)
from .schedule.parallel import (
    ParallelMode,
    ParallelStrategy,
    WorkUnit,
    DataParallel,
    TensorParallel,
    PipelineParallel,
    ClusterParallel,
    TensorParallelMerge,
    PipelineChain,
    SectionViolation,
    assign_key_sections,
    assign_sections,
    section_of,
    shard_round_robin,
)

__version__ = "0.5.0"

__all__ = [
    "Contract",
    "ContractError",
    "stable_hash",
    "Diff",
    "EvidenceCard",
    "Evolvable",
    "VersionVector",
    "vv_dominates",
    "vv_staleness",
    "Ledger",
    "Snapshot",
    "CASConflict",
    "GitError",
    "LedgerFailure",
    "ContractRejected",
    "ThreeLayerVerifier",
    "VerifierBudget",
    "AuditScheduler",
    "Dataset",
    "split_dataset",
    "backends",
    "baselines",
    "dataloader",
    "DifficultyWeighted",
    "RoundRobin",
    "TaskSampler",
    "ReflectiveFusion",
    "KeepContradictions",
    "DefaultConflict",
    "DefaultFusion",
    "reflective_merge",
    "GroupAdvantage",
    "AdvantageAcceptance",
    "AdvantageConflict",
    "AdaptiveTrustRegion",
    "TrustRegion",
    "StableDistanceAcceptance",
    "state_distance",
    "SelectionPolicy",
    "SelectionContext",
    "Candidate",
    "SingleHead",
    "Beam",
    "ParetoFrontier",
    "Archive",
    "CostEfficient",
    "MCTS",
    "MultiHeadUnsupported",
    "pareto_front",
    "ResumeQueue",
    "DurationEstimator",
    "lpt_schedule",
    "fifo_makespan",
    "TaskCluster",
    "TaskScheduler",
    "Layer",
    "classify",
    "assert_mutable",
    "GovernanceError",
    "FAST_MAX",
    "FROZEN_IDS",
    "L1SerialGate",
    "Aggregator",
    "AggregatorConfig",
    "AggregatorProtocol",
    "AggregatorFactory",
    "MergeReport",
    "MergeOutcome",
    "AggregatorContractError",
    "PopulationAggregator",
    "population_factory",
    "diffs_conflict",
    "diffs_contradict",
    "fuse_diffs",
    "EvidenceBuffer",
    "StaleAction",
    "StalenessPolicy",
    "FullStaleness",
    "GuardedStaleness",
    "ReflectiveStaleness",
    "get_policy",
    "Policies",
    "AcceptancePolicy",
    "AcceptDecision",
    "ConflictPolicy",
    "FusionPolicy",
    "FusionTrial",
    "FusionStats",
    "PromotionPolicy",
    "Promotion",
    "ProposalPolicy",
    "ProposalContext",
    "MergeContext",
    "VerifierProtocol",
    "LedgerProtocol",
    "SandboxSpec",
    "SandboxPool",
    "SharedSandboxPool",
    "Executor",
    "CacheProtocol",
    "MemoryCache",
    "FileCache",
    "ThreadExecutor",
    "ProcessExecutor",
    "Result",
    "Ref",
    "RefError",
    "RolloutSpec",
    "WorkspaceProvider",
    "LocalWorkspaceSandbox",
    "SandboxProvider",
    "Sandbox",
    "AgentDescent",
    "RoundStat",
    "run_fork_baseline",
    "AsyncAgentDescent",
    "AsyncConfig",
    "AsyncStats",
    "ParallelMode",
    "ParallelStrategy",
    "WorkUnit",
    "ClusterParallel",
    "DataParallel",
    "TensorParallel",
    "PipelineParallel",
    "TensorParallelMerge",
    "PipelineChain",
    "SectionViolation",
    "assign_sections",
    "assign_key_sections",
    "section_of",
    "shard_round_robin",
    "Completion",
    "codex",
    "dsh",
    "opencode",
    "claude_code",
    "cli_agent",
    "WorkspaceAgent",
    "AgentError",
    "Usage",
    "metered",
    "claude",
    "echo",
    "from_callable",
    "openai_compatible",
    "anthropic_compatible",
    "with_retries",
    "Agent",
    "LLMAgent",
    "reflector",
    "Task",
    "EvolvingArtifact",
    "Strategy",
    "AppendRules",
    "KeyedRules",
    "SingleSlot",
    "EvolutionResult",
    "RewardContractError",
    "ProposalContractError",
    "SOLVED",
    "tasks_from",
    "RoundInfo",
    "evolve",
    "SCORERS",
    "scorer",
    "command_scorer",
    "GraderError",
    "EvolveSpec",
    "SpecError",
    "compose",
    "load_spec",
    "run_spec",
    "meta_evolve",
    "meta_validate",
    "evolve_problem",
    "MetaOutcome",
    "SlotSpec",
    "ParamSlot",
    "SourceSlot",
    "PrioritySelection",
    "PRIORITY_SEED",
    "SLOTS",
    "auc",
    "final_reward",
    "rollouts_to",
    "slot_reflector",
    "transfer_ratio",
    "compile_priority",
    "priority_selection",
    "SLOT_PROTOCOLS",
    "compile_policy_source",
    "policy_source",
    "seed_source",
    "TreeError",
    "TreeSpec",
    "canonical",
    "load_tree",
    "materialize",
    "parse_tree",
    "tree_summary",
    "EDIT_PROTOCOL",
    "FileTree",
    "parse_edits",
    "tree_reflector",
    "LAYOUTS",
    "TEST_FAILURE_MARKER",
    "code_runner",
    "tree_runner",
    "gated_reward",
    "plugin_runner",
    "PluginHost",
    "PLUGIN_HOSTS",
    "PLUGIN_FROZEN",
    "worker_env",
    "async_evolve",
    "claude_agent",
    "rule_id",
    # the sparse audit layer: a cheap verifier paired against ground truth
    "AuditedReward",
    "AuditRecord",
    "AuditStore",
    "DeferredOracle",
    "GoldAnswer",
    "NullOracle",
    "Purpose",
    "RenderTap",
    "resolve_from_mapping",
    "verifier_fingerprint",
    "residual_bias",
    # the cost-aware search layer
    "BudgetGovernor",
    "CallBudget",
    "budgeted_completion",
]
